default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dm_development

test:
  <<: *default
  database: dm_test

production:
  <<: *default
  database: dm_production
  username: dev
  password: <%= ENV['DISRUPTIONSMAP_DATABASE_PASSWORD'] %>
